language: php

sudo: false

# Test main supported versions of PHP against latest WP.
php:
  - 5.4
  - 5.6
  - 7.0
  - 7.1
  - 7.2


before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

script: 
  - bash build.sh

env:
  - WP_VERSION=latest WP_MULTISITE=0

